name: ShootWorld
version: '${project.version}'
main: me.emxion.shootworld.ShootWorld
api-version: '1.21.1'
commands:
  SWGive:
    description: Give item from the plugin ShootWorld
    usage: /SWGive [player] [itemName]
    aliases: swg
    permission: op

  SWStart:
    description: start a game
    usage: /SWStart [Gamemode]
    aliases: sws
    permission: op
  loadout:
    description: choose and modify your loadout
    usage: /loadout